################################ FLASK ##################################
FLASK_RUN_HOST: '0.0.0.0'
FLASK_RUN_PORT: '8080'  # e.g., 9055
FLASK_DEBUG: True

API_TITLE: 'KLMS Data API'
API_VERSION: '0.0.2'
API_SPEC_FORMAT: 'json'

API_AUTO_SERVERS: True
API_AUTO_TAGS: False
API_AUTO_OPERATION_SUMMARY: True
API_AUTO_OPERATION_DESCRIPTION: True

API_TAGS: [{'name': 'KLMS', 'description': 'Knowledge Lake Management System'},{'name': 'STELAR', 'description': 'Spatio-TEmporal Linked data tools for the AgRi-food data space'}]
API_DESCRIPTION: 'Data API for managing resources in STELAR Knowledge Lake Management System'
API_TERMS_OF_SERVICE: 'http://stelar-project.eu/'
API_CONTACT: {'name': 'API Support', 'url': '<API-URL>','email': '<CONTACT-EMAIL_ADDRESS>'}
API_LICENSE: {'name': 'Apache 2.0','url': 'http://www.apache.org/licenses/LICENSE-2.0.html' }
API_SECURITY_SCHEMES: {'ApiKeyAuth': {'type': 'apiKey','in': 'header', 'name': 'Api-Token' } }

################################ CKAN ###################################
# URL to CKAN API
CKAN_API: 'http://<CKAN-HOST>/api/3/action/'

########################### PostgreSQL ################################
# Connection details
dbname: '<DB-NAME>'
dbuser: '<DB-USERNAME>'
dbpass: '<DB-PASSWORD>'
dbhost: '<DB-HOST>'  # localhost
dbport: '<DB-PORT>'  # e.g., 5432

############################## ONTOP ##################################
# URL to SPARQL endpoint
SPARQL_ENDPOINT: 'http://<ONTOP-HOST>/sparql'

################################ RANKING ###################################
# Default ranking preferences
RANK_DEFAULT_TOPK: 10
RANK_MAX_TOPK: 10000
RANK_AGG_ALGORITHM: 'Bordacount'

############################## MINIO ##################################
MINIO_ENDPOINT: '<MINIO-HOST>'
MINIO_ACCESS_KEY: '<ACCESS_KEY>'
MINIO_SECRET_KEY: '<SECRET_KEY>'
MINIO_BUCKET: '<BUCKET>'

############################## CURRENT ##################################
API_URL: 'http://tb.petrounetwork.gr/'


#############################  Task Execution  ###########################

#
# Configure the execution engine. Examples:
#

#execution:
#   engine: docker

#execution:
#    engine: kubernetes
#    namespace: playground

