# This file contains sample configuration for running the 
# python tests that require a running cluster, or initialize
# a service.
# 
# For these tests to work, you have to copy this file to
# ```
# pytest_cluster_config.yaml
# ````
# and possibly adjust the settings to reflect your own test
# setup.

sample_testcluter:
    execution:
        engine: kubernetes
        namespace: default

